package com.alexanderfisher.hibernate.entities;
// Generated by Hibernate Tools 5.4.17.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GalleriesEntity generated by hbm2java
 */
@Entity
@Table(name="galleries"
    ,catalog="portfolio"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cover_id"), @UniqueConstraint(columnNames="slug")} 
)
public class GalleriesEntity  implements java.io.Serializable {


     private Integer id;
     private ImagesEntity imagesEntity;
     private String title;
     private String slug;
     private Set<ProjectsEntity> projectsEntities = new HashSet<ProjectsEntity>(0);
     private Set<ImagesEntity> imagesEntities = new HashSet<ImagesEntity>(0);

    public GalleriesEntity() {
    }

	
    public GalleriesEntity(String title, String slug) {
        this.title = title;
        this.slug = slug;
    }
    public GalleriesEntity(ImagesEntity imagesEntity, String title, String slug, Set<ProjectsEntity> projectsEntities, Set<ImagesEntity> imagesEntities) {
       this.imagesEntity = imagesEntity;
       this.title = title;
       this.slug = slug;
       this.projectsEntities = projectsEntities;
       this.imagesEntities = imagesEntities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cover_id", unique=true)
    public ImagesEntity getImagesEntity() {
        return this.imagesEntity;
    }
    
    public void setImagesEntity(ImagesEntity imagesEntity) {
        this.imagesEntity = imagesEntity;
    }

    
    @Column(name="title", nullable=false, length=90)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="slug", unique=true, nullable=false, length=128)
    public String getSlug() {
        return this.slug;
    }
    
    public void setSlug(String slug) {
        this.slug = slug;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="galleriesEntity")
    public Set<ProjectsEntity> getProjectsEntities() {
        return this.projectsEntities;
    }
    
    public void setProjectsEntities(Set<ProjectsEntity> projectsEntities) {
        this.projectsEntities = projectsEntities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="galleriesEntity")
    public Set<ImagesEntity> getImagesEntities() {
        return this.imagesEntities;
    }
    
    public void setImagesEntities(Set<ImagesEntity> imagesEntities) {
        this.imagesEntities = imagesEntities;
    }




}


