package com.alexanderfisher.hibernate.entities;
// Generated by Hibernate Tools 5.4.17.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProjectsEntity generated by hbm2java
 */
@Entity
@Table(name="projects"
    ,catalog="portfolio"
    , uniqueConstraints = {@UniqueConstraint(columnNames="gallery_id"), @UniqueConstraint(columnNames="slug")} 
)
public class ProjectsEntity  implements java.io.Serializable {


     private Integer id;
     private CategoriesEntity categoriesEntity;
     private GalleriesEntity galleriesEntity;
     private String title;
     private String slug;
     private String subtitle;
     private String tagline;
     private String intro;
     private String content;
     private String subcontent;

    public ProjectsEntity() {
    }

	
    public ProjectsEntity(String title, String slug, String subtitle, String tagline, String intro, String content, String subcontent) {
        this.title = title;
        this.slug = slug;
        this.subtitle = subtitle;
        this.tagline = tagline;
        this.intro = intro;
        this.content = content;
        this.subcontent = subcontent;
    }
    public ProjectsEntity(CategoriesEntity categoriesEntity, GalleriesEntity galleriesEntity, String title, String slug, String subtitle, String tagline, String intro, String content, String subcontent) {
       this.categoriesEntity = categoriesEntity;
       this.galleriesEntity = galleriesEntity;
       this.title = title;
       this.slug = slug;
       this.subtitle = subtitle;
       this.tagline = tagline;
       this.intro = intro;
       this.content = content;
       this.subcontent = subcontent;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id")
    public CategoriesEntity getCategoriesEntity() {
        return this.categoriesEntity;
    }
    
    public void setCategoriesEntity(CategoriesEntity categoriesEntity) {
        this.categoriesEntity = categoriesEntity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gallery_id", unique=true)
    public GalleriesEntity getGalleriesEntity() {
        return this.galleriesEntity;
    }
    
    public void setGalleriesEntity(GalleriesEntity galleriesEntity) {
        this.galleriesEntity = galleriesEntity;
    }

    
    @Column(name="title", nullable=false, length=60)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="slug", unique=true, nullable=false, length=128)
    public String getSlug() {
        return this.slug;
    }
    
    public void setSlug(String slug) {
        this.slug = slug;
    }

    
    @Column(name="subtitle", nullable=false, length=60)
    public String getSubtitle() {
        return this.subtitle;
    }
    
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    
    @Column(name="tagline", nullable=false, length=100)
    public String getTagline() {
        return this.tagline;
    }
    
    public void setTagline(String tagline) {
        this.tagline = tagline;
    }

    
    @Column(name="intro", nullable=false)
    public String getIntro() {
        return this.intro;
    }
    
    public void setIntro(String intro) {
        this.intro = intro;
    }

    
    @Column(name="content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="subcontent", nullable=false)
    public String getSubcontent() {
        return this.subcontent;
    }
    
    public void setSubcontent(String subcontent) {
        this.subcontent = subcontent;
    }




}


