package com.alexanderfisher.hibernate.dto;
// Generated by Hibernate Tools 5.4.17.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer id;
     private String slug;
     private String title;
     private String subtitle;
     private String description;
     private Set projectses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(String slug, String title, String subtitle, String description) {
        this.slug = slug;
        this.title = title;
        this.subtitle = subtitle;
        this.description = description;
    }
    public Categories(String slug, String title, String subtitle, String description, Set projectses) {
       this.slug = slug;
       this.title = title;
       this.subtitle = subtitle;
       this.description = description;
       this.projectses = projectses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSlug() {
        return this.slug;
    }
    
    public void setSlug(String slug) {
        this.slug = slug;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSubtitle() {
        return this.subtitle;
    }
    
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getProjectses() {
        return this.projectses;
    }
    
    public void setProjectses(Set projectses) {
        this.projectses = projectses;
    }




}


