package com.alexanderfisher.hibernate.dto;
// Generated Jun 11, 2020, 6:22:40 PM by Hibernate Tools 5.4.17.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Galleries generated by hbm2java
 */
@Entity
@Table(name="galleries"
    ,catalog="portfolio"
    , uniqueConstraints = {@UniqueConstraint(columnNames="cover_id"), @UniqueConstraint(columnNames="slug")} 
)
public class Galleries  implements java.io.Serializable {


     private Integer id;
     private Images images;
     private String title;
     private String slug;
     private Set projectses = new HashSet(0);
     private Set imageses = new HashSet(0);

    public Galleries() {
    }

	
    public Galleries(String title, String slug) {
        this.title = title;
        this.slug = slug;
    }
    public Galleries(Images images, String title, String slug, Set projectses, Set imageses) {
       this.images = images;
       this.title = title;
       this.slug = slug;
       this.projectses = projectses;
       this.imageses = imageses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cover_id", unique=true)
    public Images getImages() {
        return this.images;
    }
    
    public void setImages(Images images) {
        this.images = images;
    }

    
    @Column(name="title", nullable=false, length=90)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="slug", unique=true, nullable=false, length=128)
    public String getSlug() {
        return this.slug;
    }
    
    public void setSlug(String slug) {
        this.slug = slug;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="galleries")
    public Set getProjectses() {
        return this.projectses;
    }
    
    public void setProjectses(Set projectses) {
        this.projectses = projectses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="galleries")
    public Set getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set imageses) {
        this.imageses = imageses;
    }




}


