package com.alexanderfisher.hibernate.dto;
// Generated by Hibernate Tools 5.4.17.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Images generated by hbm2java
 */
public class Images  implements java.io.Serializable {


     private Integer id;
     private Galleries galleries;
     private String filename;
     private String alt;
     private Set gallerieses = new HashSet(0);

    public Images() {
    }

	
    public Images(String filename, String alt) {
        this.filename = filename;
        this.alt = alt;
    }
    public Images(Galleries galleries, String filename, String alt, Set gallerieses) {
       this.galleries = galleries;
       this.filename = filename;
       this.alt = alt;
       this.gallerieses = gallerieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Galleries getGalleries() {
        return this.galleries;
    }
    
    public void setGalleries(Galleries galleries) {
        this.galleries = galleries;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public String getAlt() {
        return this.alt;
    }
    
    public void setAlt(String alt) {
        this.alt = alt;
    }
    public Set getGallerieses() {
        return this.gallerieses;
    }
    
    public void setGallerieses(Set gallerieses) {
        this.gallerieses = gallerieses;
    }




}


