package com.alexanderfisher.hibernate.dto;
// Generated by Hibernate Tools 5.4.17.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name="images"
    ,catalog="portfolio"
)
public class Images  implements java.io.Serializable {


     private Integer id;
     private Galleries galleries;
     private String filename;
     private String alt;
     private Set<Galleries> gallerieses = new HashSet<Galleries>(0);

    public Images() {
    }

	
    public Images(String filename, String alt) {
        this.filename = filename;
        this.alt = alt;
    }
    public Images(Galleries galleries, String filename, String alt, Set<Galleries> gallerieses) {
       this.galleries = galleries;
       this.filename = filename;
       this.alt = alt;
       this.gallerieses = gallerieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gallery_id")
    public Galleries getGalleries() {
        return this.galleries;
    }
    
    public void setGalleries(Galleries galleries) {
        this.galleries = galleries;
    }

    
    @Column(name="filename", nullable=false)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="alt", nullable=false)
    public String getAlt() {
        return this.alt;
    }
    
    public void setAlt(String alt) {
        this.alt = alt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="images")
    public Set<Galleries> getGallerieses() {
        return this.gallerieses;
    }
    
    public void setGallerieses(Set<Galleries> gallerieses) {
        this.gallerieses = gallerieses;
    }




}


