package com.alexanderfisher.hibernate.dto;
// Generated by Hibernate Tools 5.4.17.Final



/**
 * Projects generated by hbm2java
 */
public class Projects  implements java.io.Serializable {


     private Integer id;
     private Categories categories;
     private Galleries galleries;
     private String title;
     private String slug;
     private String subtitle;
     private String tagline;
     private String intro;
     private String content;
     private String subcontent;

    public Projects() {
    }

	
    public Projects(String title, String slug, String subtitle, String tagline, String intro, String content, String subcontent) {
        this.title = title;
        this.slug = slug;
        this.subtitle = subtitle;
        this.tagline = tagline;
        this.intro = intro;
        this.content = content;
        this.subcontent = subcontent;
    }
    public Projects(Categories categories, Galleries galleries, String title, String slug, String subtitle, String tagline, String intro, String content, String subcontent) {
       this.categories = categories;
       this.galleries = galleries;
       this.title = title;
       this.slug = slug;
       this.subtitle = subtitle;
       this.tagline = tagline;
       this.intro = intro;
       this.content = content;
       this.subcontent = subcontent;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Galleries getGalleries() {
        return this.galleries;
    }
    
    public void setGalleries(Galleries galleries) {
        this.galleries = galleries;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSlug() {
        return this.slug;
    }
    
    public void setSlug(String slug) {
        this.slug = slug;
    }
    public String getSubtitle() {
        return this.subtitle;
    }
    
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }
    public String getTagline() {
        return this.tagline;
    }
    
    public void setTagline(String tagline) {
        this.tagline = tagline;
    }
    public String getIntro() {
        return this.intro;
    }
    
    public void setIntro(String intro) {
        this.intro = intro;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getSubcontent() {
        return this.subcontent;
    }
    
    public void setSubcontent(String subcontent) {
        this.subcontent = subcontent;
    }




}


