package com.alexanderfisher.hibernate.dto;
// Generated by Hibernate Tools 5.4.17.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String role;
     private Set userses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(String name, String role) {
        this.name = name;
        this.role = role;
    }
    public Roles(String name, String role, Set userses) {
       this.name = name;
       this.role = role;
       this.userses = userses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


