package com.alexanderfisher.hibernate.dto;
// Generated by Hibernate Tools 5.4.17.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String salt;
     private String password;
     private String email;
     private boolean isActive;
     private Set roleses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String salt, String password, String email, boolean isActive) {
        this.username = username;
        this.salt = salt;
        this.password = password;
        this.email = email;
        this.isActive = isActive;
    }
    public Users(String username, String salt, String password, String email, boolean isActive, Set roleses) {
       this.username = username;
       this.salt = salt;
       this.password = password;
       this.email = email;
       this.isActive = isActive;
       this.roleses = roleses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public Set getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set roleses) {
        this.roleses = roleses;
    }




}


