swagger: '2.0'
info:
  title: Portfolio API
  version: '1.0.0'
  contact:
    name: Alexander Fisher
    email: afisher@alexander-fisher.com
paths:
  /categories:
    get:
      operationId: getCategories
      description: Returns all categories
      produces:
        - application/json
      responses:
        '200':
          description: A list of categories
          schema:
            type: array
            items:
              $ref: '#/definitions/Category'
  /categories/{categoryId}/projects:
    get:
      operationId: getCategoryProjects
      description: Returns projects for a given category
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/CategoryId'
      responses:
        '200':
          description: A list of projects for a given category
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
  /projects:
    get:
      operationId: getProjects
      description: Returns all projects
      produces:
        - application/json
      responses:
        '200':
          description: A list of projects
          schema:
            type:
              array
            items:
              $ref: '#/definitions/Project'
  /projects/{projectId}/gallery:
    get:
      operationId: getProjectGallery
      description: Returns project gallery data for a project
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/ProjectId'
      responses:
        '200':
          description: Project gallery data for a project
          schema:
            $ref: '#/definitions/ProjectGallery'
parameters:
  CategoryId:
    name: categoryId
    in: path
    type: integer
    required: true
  ProjectId:
    name: projectId
    in: path
    type: integer
    required: true
definitions:
  Category:
    type: object
    properties:
      id:
        type: integer
      slug:
        type: string
      title:
        type: string
      subtitle:
        type: string
      description:
        type: string
  Gallery:
    type: object
    properties:
      id:
        type: integer
      coverId:
        type: integer
      title:
        type: string
      slug:
        type: string
  Image:
    type: object
    properties:
      id:
        type: integer
      galleryId:
        type: integer
      filename:
        type: string
      alt:
        type: string
  Project:
    type: object
    properties:
      id:
        type: integer
      categoryId:
        type: integer
      title:
        type: string
      slug:
        type: string
      subtitle:
        type: string
      tagline:
        type: string
      intro:
        type: string
      content:
        type: string
      subcontent:
        type: string
  ProjectGallery:
    type: object
    properties:
      gallery:
        $ref: '#/definitions/Gallery'
      images:
        type: array
        items:
          $ref: '#/definitions/Image'
